# Generated by Django 4.2.3 on 2023-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('text', models.TextField(verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время создания')),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('title',),
            },
        ),
    ]
