# Generated by Django 4.2.3 on 2023-08-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='time')),
                ('start', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='start time')),
                ('finish', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='finish time')),
                ('periodicity', models.CharField(choices=[('onetime', 'onetime'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=150, verbose_name='periodicity')),
                ('status', models.CharField(choices=[('was created', 'was created'), ('was ended', 'was ended'), ('is active', 'active')], default='was created', max_length=100, verbose_name='status')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'mailing list',
                'verbose_name_plural': 'mailing lists',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingmessage', verbose_name='message'),
        ),
    ]
