# Generated by Django 4.2.3 on 2023-08-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailinglist_mailingmessage_delete_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='client_id',
            field=models.ManyToManyField(to='main.client', verbose_name='client id'),
        ),
        migrations.CreateModel(
            name='MailingListLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='send time')),
                ('status', models.CharField(choices=[('was sent', 'sent'), ('sending error', 'sending error')], verbose_name='status')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response from server')),
                ('mailing_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailinglist', verbose_name='mailing list id')),
            ],
            options={
                'verbose_name': 'mailing effort',
                'verbose_name_plural': 'mailing efforts',
            },
        ),
    ]
