# Generated by Django 4.2.4 on 2023-08-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mailinglist_client_id_mailinglistlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistlogs',
            options={'verbose_name': 'mailing effort log', 'verbose_name_plural': 'mailing efforts log'},
        ),
        migrations.AddField(
            model_name='mailinglistlogs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='client'),
        ),
    ]
