# Generated by Django 4.2.4 on 2023-08-22 09:50

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mailinglistlogs_options_mailinglistlogs_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'get_latest_by': 'email', 'ordering': ('last_name',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'get_latest_by': 'time', 'verbose_name': 'mailing list', 'verbose_name_plural': 'mailing lists'},
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='finish',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='finish time UTC'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='start',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='start time UTC'),
        ),
    ]
